advanced/Recursive/Recursive.java
- add advanced folder
- add Recursive.java
- Menambahkan folder advanced karena rekursif merupakan topik advanced
- Menambahkan kelas Recursive.java
- ``os`` = ``macOS``
- ``java`` = ``JAVA 16.0.1``
=> add: topik recursive function

basic/BasicLooping/DoWhile.java, basic/BasicLooping/README.md
- ``os`` = ``linux / windows / macOS``
- ``java`` = ``javac -V (unix) / javac -V ( windows )``
=> add: menambahkan algoritma DoWhile pada folder BasicLooping

.gitignore, CONTRIBUTING.md
- ``java`` = ``javac -V ( windows )``
=> docs: enhance docs

conversion/DecimalToBinary.java
- ``os`` = ``linux / windows / macOS``
- ``java`` = ``javac -V (unix) / javac -V ( windows )``
=> add: menambahkan konversi bilangan desimal ke biner

conversion/OctalToDecimal.java
- ``os`` = ``linux``
- ``java`` = ``8``
linked issue #43
=> feat: algoritma mengubah oktal ke desimal

intermediate/JavaAbstrac/README.md, intermediate/JavaAbstrac/abstrakTutorial.java
Menambahkan contoh penggunaan java abstrak
- ``os`` = ``linux``
- ``java`` = ``8``
linked issue #52
=> feat: menambahkan java abstrak

README.md
=> feat: menambahkan badge discord

intermediate/JavaDate/JavaDate.java, intermediate/JavaDate/README.md
Menambahkan cara mendapat dan mengubah informasi tanggal dan waktu di Java
- ``os`` = ``linux``
- ``java`` = ``8``
linked issue #56
=> feat: menambah java date

intermediate/JavaEnum/Main.java, intermediate/JavaEnum/README.md
- ``os`` = ``macOS``
- ``java`` = ``11.0.2``
linked issue #54
=> feat: adding java enum

README.md
Saya memperbaharuiraui README.md sesuai dengan issue #61 
- ``os`` = ``linux / windows / macOS``
- ``java`` = ``javac -V (unix) / javac -V ( windows )``
linked issue #61
=> docs: Revolusi README.md

learn/advanced/Java-GUI/README.md, learn/advanced/Java-GUI/Swing/JPanel-with-JLabel/Clean-JPanel/MembuatGUISendiri.java, learn/advanced/Java-GUI/Swing/JPanel-with-JLabel/Colorful-JPanel/ContohPanel.java, learn/advanced/Java-GUI/Swing/README.md
Saya menambahakan Materi baru yakni `Java Advance`  yakni `Java GUI`
- ``os`` = ``linux / windows / macOS``
- ``java`` = ``javac -V (unix) / javac -V ( windows )``
linked issue #62
=> feat: Menambahkan Java GUI

learn/intermediate/UserInput/README.md, learn/intermediate/UserInput/UserInput.java
Menambahkan kode program cara menggunakan dan mengambil standar input user dengan ```Scanner```. Serta menambahkan dokumentasi tentang java user input kususnya ```Scanner``` 
- ``os`` = ``linux``
- ``java`` = ``11.0.13``
linked issue #55
=> feat: java user input

algorithm/Sorting/BubbleSort.java
=> feat: Algoritma Bubble Sort

algorithm/Sorting/SelectionSort.java
=> feat: Algoritma Selection Sort

learn/advanced/Java-GUI/Swing/JPanel-with-JButton/JButtonJPanel.java
Menambahkan GUI Java yakni JButton pada Java
- ``java`` = `` javac -V ( windows )``
linked issue #62
=> feat: Menambahkan program baru

algorithm/data-structure/Array/ArrayDimensiSatu/ArraySatuD.java, algorithm/data-structure/Array/ArrayDimensiSatu/README.md, algorithm/data-structure/Array/README.md
Menambahkan Struktur Data yakni Array
- ``java`` = ``javac -v ( Windows )``
linked issue #76
=> feat: Menambahkan Algoritma dan Dokumentasi baru

algorithm/data-structure/Sorting/README.md
=> docs: dokumentasi untuk folder sorting

learn/basic/Array/README.md
Menambahkan Dokumentasi baru yakni pengertian dan definisi Array
- ``java`` = ``javac -V ( windows )``
=> docs: Menambahkan Dokumentasi baru

learn/basic/Operator/README.md, learn/basic/Operator/Unary/Bitwise.java, learn/basic/Operator/Unary/IncreDecre.java, learn/basic/Operator/Unary/Negation.java
Saya menambahkan Materi basic baru yakni Opeator Unary dan juga dokumentasi pada operator
- ``java`` = ``javac -V ( windows )``
=> feat: Menambahkan Algoirtma baru

learn/basic/MethodJava/MethodOverriding/MethodOverriding.java, learn/basic/MethodJava/MethodOverriding/README.md
Saya telah menambah materi Method Overriding beserta dokumentasinya
- ``java`` = ``javac -V ( windows )``
=> add: Menambah Algoritma baru (MethodOverriding) beserta dokumentasi

README.md
Ada beberapa tata bahasa dan penulisan yang saya perbaiki di README.md:
- Mengganti beberapa _text alternative_ pada gambar agar lebih jelas.
- Memperbaiki typo penulisan.
- Pengubahan tata letak kalimat.
- Menghapus kata berulang.
- Menyusun kalimat berdasarkan judul.
- Mengganti beberapa istilah.
- Penggunaan kata subjek secara konsisten.
Saya menggunakan:
- OS = GNU/Linux
- Markdown = GitHub
=> docs: memperbaiki bahasa dan tulisan README.md

algorithm/data-structure/Queue/README.md, algorithm/data-structure/Queue/SourceCode/ContohQueue.java
Saya menambahkan Materi pemrograman baru dalam repo struktur data yakni Queue (Antrian)
- ``java`` = ``javac -V ( Windows )``
linked issue #76
=> add: Menambahkan Algoritma dan Dokumentasi Baru

learn/basic/StrukturKontrol/SwitchLambda/README.md, learn/basic/StrukturKontrol/SwitchLambda/SwitchLambda.java, learn/basic/StrukturKontrol/SwitchYield/README.md, learn/basic/StrukturKontrol/SwitchYield/SwitchYield.java
Saya menambahkan materi switch lambda dan yield di basic.
Saya menggunakan:
- ``OS`` = ``Windows 10``
- ``Java`` = ``OpenJDK 17.0.2 ``
=> feat: menambahkan materi switch lambda & yield

.github/workflows/build.yml
menambahkan git action untuk build hasil kode dengan perintah maven ``batch-mode``
=> Menambahkan action untuk test build project maven java

README.md
Ada sedikit perubahan yang saya perbaiki di README.md:
- Memperbaiki typo penulisan.
- Menambahkan _source link_.
Saya menggunakan:
- OS = Windows
- Markdown = GitHub
=> docs: perbaikan typo dokumentasi README

.github/ISSUE_TEMPLATE/feature_report.md, .github/pull_request_template.md
- ``java`` = ``Oracle JDK 17``
Issues : #104
=> docs: Menambahkan Dokumentasi

src/main/java/maths/GCD.java
- ``Java`` = ``18.0``
Issues : #
=> add: menambahkan program faktor persekutuan terbesar

src/main/java/maths/GCD.java
Fix workflow gagal build
- ``Java`` = `18`
Issues : #
=> fix: Memperbaharui kode program

src/main/java/algorithm/datastructure/Search/LinearSearch.java, src/main/java/algorithm/datastructure/Search/README.md, src/main/java/maths/GCD.java
menambahkan linear search
- ``OS`` = `Mac OS`
- ``Java`` = `18`
Issues : #76
=> Linearsearch

README.md
`Visitor Badge` punya om Feri Irawan hilang. ntah sudah mati masa berlakunya atau mati sendiri. Selain itu ingin mmenguji `Protected Branch` yang dimana setiap contributor atau admmin repository harus melakukan `pull_request` sebelum mengedit _source_code_ nya sendiri.
- ``Java`` =  18
=> docs: Menutup Visitor Badge sementara karena hilang

src/main/java/learn/intermediate/object_oriented_programming/oop_intermediate/README.md
Memperbaiki alamat URL pada [README.md oop_intermediate](https://github.com/bellshade/Java/blob/main/src/main/java/learn/intermediate/object_oriented_programming/oop_intermediate/README.md)
- ``OS`` = `Linux`
- ``Java`` = `18`
=> docs: fix alamat URL pada README.md oop_intermediate

src/main/java/learn/basic/MathJava/MathJava.java
Menambahkan fungsi Math.PI dan Math.round() dan menjelaskan tentang kegunaannya. 
- [x ] Saya menambah algoritma terbaru.
- [ x] Saya memperbaiki algoritma yang sudah ada.
- [ x] Saya memperbaiki dokumentasi.
- [✅ ] Saya menambah dokumentasi.
- [ ✅] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/Java/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
- [✅ ] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
- [✅ ] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.
Mac OS
- ``OS`` = `Windows/Linux/Mac OS` 
- ``Java`` = 
Issues : #
=> add: menambah PI dan pembulatan angka

src/main/java/maths/GCD.java, src/main/java/utilities/JavaCalendar/JavaCalendar.java, src/main/java/utilities/JavaCalendar/README.md
- Saya memberikan penjelasan tentang penggunaan class Java Calendar.
- #118  .
- ``Java`` =  `javac`
Issues :  #118
=> add: penjelasan Java Calendar, fix: error package name

src/test/java/ArrangeActAssertPatternTest.java
Saya menambahkan code baru di bagian test. Disini saya membuat 1 file java dengan nama `ArrangeActAssertPatternTest.java`.  Didalamnya terdapat unit test yang menerapkan pattern AAA `(Arrange, Act, Assert)` . Saya menjelaskan bagaimana cara menulis sebuah test case yang baik dan rapi agar lebih mudah dibaca. Serta memberi contoh perbandingan antara unit test yang baik dengan yang kurang baik.
- ``Java`` = `Intellij IDEA Community Edition`
=> feat: add sample unit test using AAA (Arrange, Act, Assert) pattern

src/main/java/learn/advanced/GuessTheNumber/GuessTheNumber.java, src/main/java/learn/advanced/GuessTheNumber/README.md
Saya menambahkan package baru dengan nama `GuessTheNumber` didalam package `advanced`. Disini terdapat 2 file baru yaitu `GuessTheNumber.java` dan `README.md`.  
Guess The Number adalah permainan untuk menebak angka random yang digenerate oleh code. 
- ``Java`` = `Intellij Idea Community Edition`
=> Add guess the number game to package advanced

src/main/java/learn/advanced/RockPaperScissors/Move.java, src/main/java/learn/advanced/RockPaperScissors/README.md, src/main/java/learn/advanced/RockPaperScissors/RockPaperScissors.java
Saya menambahkan code baru di package `advanced`. Saya membuat games rock paper scissors. Disini saya membuat package baru `RockPaperScissors` berisi 3 file yaitu `RockPaperScissors.java` `Move.java` `README.md`. 
- ``Java`` = `Intellij IDEA Community Edition`
=> feat: add code and documentation for "rock paper scissors" game

src/main/java/utilities/JavaIterator/JavaIterator.java, src/main/java/utilities/JavaIterator/README.md
Saya memberikan penjelasan tentang penggunaan class Java Iterator.
- ``Java`` = `javac` 
Label HACKTOBERFEST-ACCEPTED
=> add: penjelasan JavaIterator

src/main/java/learn/intermediate/JavaGeneric/AbstractGenericClass/JavaAbstractGeneric.java, src/main/java/learn/intermediate/JavaGeneric/AbstractGenericClass/MainGenericClass.java, src/main/java/learn/intermediate/JavaGeneric/AbstractGenericClass/Pakaian.java, src/main/java/learn/intermediate/JavaGeneric/AbstractGenericClass/README.md, src/main/java/learn/intermediate/JavaGeneric/AbstractGenericClass/model/Baju.java, src/main/java/learn/intermediate/JavaGeneric/AbstractGenericClass/model/Celana.java
Menambah contoh penggunaan java generic pada class abstrak 
- ``Java`` = 18 
Issues : #126
=> add: menambah java abstract generic

src/main/java/learn/intermediate/JavaGeneric/GenericClassMultiParameter/GenericClassMultiParameter.java, src/main/java/learn/intermediate/JavaGeneric/GenericClassMultiParameter/README.md, src/main/java/learn/intermediate/JavaGeneric/JavaGeneric.java, src/main/java/learn/intermediate/JavaGeneric/README.md
Menambah contoh penggunaan java generic dengan menggunakan 2 atau lebih paremeter type
- ``Java`` = 18 
Issues : #128
=> add: menambah java generic multi parameter type

src/main/java/learn/advanced/quickMath/QuickMath.java, src/main/java/learn/advanced/quickMath/ReadME.md
Menambah program game lomba menghitung cepat, program ini akan menghitung berapa waktu yang kamu butuhkan untuk tambah tambahan singkat.
- [✔️ ] Saya menambah algoritma terbaru.
- [ X] Saya memperbaiki algoritma yang sudah ada.
- [ X] Saya memperbaiki dokumentasi.
- [X ] Saya menambah dokumentasi.
- [ ✔️] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/Java/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
- [ ✔️] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
- [✔️ ] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.
- ``Java`` = 
Issues : #62
=> add: menambah program game menghitung cepat

src/main/java/algorithm/datastructure/Tree/FenwickTree.java
pohon Fenwick atau pohon berindeks biner adalah struktur data yang dapat secara efisien memperbarui elemen dan menghitung jumlah awalan dalam tabel angka.
- ``Java`` = ``18.0.2`` 
Issues : #
=> feat: menambahkan fenwick tree

README.md
Saya mengganti logo Java dengan logo baru yang "fresh"
- ``Java`` =  18
=> docs: Memperbaharui Dokumentasi

src/main/java/learn/intermediate/JavaGeneric/GenericClassBounded/AbstractEntity.java, src/main/java/learn/intermediate/JavaGeneric/GenericClassBounded/DataEntity.java, src/main/java/learn/intermediate/JavaGeneric/GenericClassBounded/Jaket.java, src/main/java/learn/intermediate/JavaGeneric/GenericClassBounded/MainGenericClassBounded.java, src/main/java/learn/intermediate/JavaGeneric/GenericClassBounded/README.md
Mejelaskan fitur java generic bounded untuk membatasi class generic di gunakan oleh class yang tidak memiliki parent yang sama
- ``Java`` = 18
Issues : #142
=> add: penjelasan generic bounded

README.md
Saya mengganti base url untuk visitor badge karna url yang sebelumnya sudah tidak dapat diaktifkan.
- ``OS`` = `Android` 
- ``Java`` = 
Issues : #
=> docs: mengganti base url visitor badge

pom.xml, src/main/java/learn/intermediate/JavaJSON/JacksonObjectMapper.java, src/main/java/learn/intermediate/JavaJSON/README.md
penambahan java json menggunakan Jackson
- ``Java`` = `11`
Issues : #11
=> add: menambahkan java json

README.md
Memperbaiki dokumentasi sementara
- ``Java`` = 18
=> docs: Mematikan sementara Visitor Badge

README.md
Saya memperbaiki dokumentasi dengan menambahkan link discord Kelas Terbuka
- ``OS`` = `Windows/Linux/Mac OS` 
- ``Java`` = 
Issues : #
=> docs: memperbaiki documentasi

src/main/java/algorithm/backtracking/Permutasi.java, src/main/java/algorithm/datastructure/Queue/SourceCode/PriorityQueue.java
menambahkan algoritma priority queue
Issues : #76
=> feat: menambahkan algoritma queue prioritas

.gitignore, src/main/java/learn/basic/Exception/Exception.java, src/main/java/learn/basic/Exception/README.md
=> feat: menambahkan materi exception

src/main/java/algorithm/datastructure/Queue/SourceCode/GenericArrayListQueue.java
menambahkan contoh kode dari generic array list queue
- ``Java`` = ``19.0.2+7``
Issues : #76
=> feat: menambahkan generic array list queue

src/main/java/learn/basic/DateTime/Instant/InstantExample.java, src/main/java/learn/basic/DateTime/LocalDate/LocalDateExample.java, src/main/java/learn/basic/DateTime/LocalDateTime/LocalDateTimeExample.java, src/main/java/learn/basic/DateTime/README.md, src/main/java/learn/basic/DateTime/ZonedDateTime/ZonedDateTimeExample.java
=> feat: menambahkan datetime

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
menambahkan docker container untuk pengguna docker
- ``Java`` = ``testing pada java 19.02 `2023-01-17``
=> add: menambahkan docker container

.devcontainer/README.md
=> add: Menambahkana Catatan dalam Dependencies

.gitignore, src/main/java/algorithm/datastructure/Tree/BinaryTree/BinaryTree.java
chore: modifikasi gitignore
menambahkan implementasi sederhana dari binary tree dan menambakan command untuk mentriget git agar file dalam folder ``.settings`` tidak terhitung, dikarenakan hanya setting lint dari jdt. informasi tentang lint jdt bisa dilihat [disini](https://github.com/mfussenegger/nvim-jdtls)
Issues : #130
=> add: menambahkan binarySearch

.classpath, .factorypath, .gitignore, .project, src/main/java/algorithm/datastructure/DynamicArray/DynamicArray.java
penjelasan tentang konsep dari array dinamis [disini](https://en.wikipedia.org/wiki/Dynamic_array)
- ``Java`` =  ``19.0.2``
Issues : #76
=> Dynamic array

src/main/java/algorithm/datastructure/LinkedList/SourceCode/DoubleLinkedList.java
menambahkan contoh dari operasi double linked list
Issues : #76
=> feat: menambahkan contoh dari double linked list

src/main/java/algorithm/datastructure/LinkedList/SourceCode/CursorLinkedList.java
menambahkan contoh dari cursor linked list
Issues : #76
=> feat: menambahkan contoh dari cursor linked list

src/main/java/algorithm/conversions/HexadecimalToBinary.java
contoh sederhana kode merubah angka heksadesimal ke bilanga biner
Issues : #69
=> feat: menambahkan contoh konversi dari heksadesimal ke biner

src/main/java/learn/intermediate/javahttpclient/HttpClientMain.java, src/main/java/learn/intermediate/javahttpclient/README.md, src/main/java/learn/intermediate/javahttpclient/dto/Firmness.java, src/main/java/learn/intermediate/javahttpclient/dto/Flavor.java, src/main/java/learn/intermediate/javahttpclient/dto/FlavorsItem.java, src/main/java/learn/intermediate/javahttpclient/dto/Item.java, src/main/java/learn/intermediate/javahttpclient/dto/NaturalGiftType.java, src/main/java/learn/intermediate/javahttpclient/dto/PokemonDetailResponse.java, src/main/java/learn/intermediate/javahttpclient/services/RestClientService.java, src/main/java/learn/intermediate/javahttpclient/services/RestClientServiceImpl.java
menambahahkan contoh implementasi penggunaan http client java
- ``Java`` =  `OpenJdk-20`
=> feat: implementasi http client java

src/main/java/learn/intermediate/javahttpclient/HttpClientMain.java, src/main/java/learn/intermediate/javahttpclient/dto/PokemonDetailResponse.java, src/main/java/learn/intermediate/javahttpclient/services/RestClientService.java, src/main/java/learn/intermediate/javahttpclient/services/RestClientServiceImpl.java, src/main/java/learn/intermediate/javarecord/JavaRecordMain.java, src/main/java/learn/intermediate/javarecord/README.md, src/main/java/learn/intermediate/javarecord/User.java, src/main/java/learn/intermediate/javarecord/recorddto/Firmness.java, src/main/java/learn/intermediate/javarecord/recorddto/Flavor.java, src/main/java/learn/intermediate/javarecord/recorddto/FlavorsItem.java, src/main/java/learn/intermediate/javarecord/recorddto/Item.java, src/main/java/learn/intermediate/javarecord/recorddto/NaturalGiftType.java, src/main/java/learn/intermediate/javarecord/recorddto/PokemonRecordResponse.java
- ``OS`` = `Windows`
- ``Java`` = `OpenJdk-20`
=> add: implementasi java record

pom.xml, src/main/java/learn/advanced/javajdbc/MainJdbc.java, src/main/java/learn/advanced/javajdbc/README.md, src/main/java/learn/advanced/javajdbc/config/JdbcConfig.java, src/main/java/learn/advanced/javajdbc/dto/PersonRequest.java, src/main/java/learn/advanced/javajdbc/dto/PersonResponse.java, src/main/java/learn/advanced/javajdbc/model/Person.java, src/main/java/learn/advanced/javajdbc/repository/BaseDao.java, src/main/java/learn/advanced/javajdbc/repository/PersonRepository.java, src/main/java/learn/advanced/javajdbc/service/PersonService.java, src/main/java/learn/advanced/javajdbc/service/PersonServiceImpl.java
- ``OS`` = `Windows`
- ``Java`` = `OpenJdk-20`
=> add: implementasi java jdbc

src/main/java/learn/advanced/JavaGUI/Swing/JPanelWithJTextField/JTextFieldJPanel.java
- ``OS`` = `Linux`
- ``Java`` = `OpenJdk-11`
=> add: menambahkan program JTextField with JPanel

src/main/java/learn/basic/TipeData/README.md
perbaiki salah ketik / typo
memperbaiki salah ketik atau typo dari kata **keil** yang seharusnya **kecil**
- ``OS`` = `Linux`
- ``Java`` = `GraalVM 17.0.8+9.1`
=> docs:  perbaiki salah ketik

pom.xml, src/main/java/maths/AngkaArmstrong.java, src/test/java/maths/AngkaArmstrongTest.java
Menambahkan fungsi angka armstrong
- ``Java`` = `22.0.2`
=> feat: menambahkan contoh angka armstrong
